name: 'Kubectl tool installer'
description: 'Install a specific version of kubectl binary. Acceptable values are latest or any semantic version string like "v1.15.0"'
inputs:
   version:
      description: 'Version of kubectl'
      required: true
      default: 'latest'
   downloadBaseURL:
      description: 'Set the download base URL'
      required: false
      default: 'https://dl.k8s.io'
outputs:
   kubectl-path:
      description: 'Path to the cached kubectl binary'
branding:
   color: 'blue'
runs:
   using: 'node24'
   main: 'lib/index.js'
