blank_issues_enabled: false
contact_links:
   - name: GitHub Action "setup-kubectl" Support
     url: https://github.com/Azure/setup-kubectl
     security: https://github.com/Azure/setup-kubectl/blob/main/SECURITY.md
     about: Please ask and answer questions here.
